### ISSUE TITLE
As a developer I want to use CSS modules and not so much inline styling

### ISSUE THREAD

**Issue by hadesrofl** [hadesrofl/price-calculator#69]
NextJS has an implicit module feature. Naming files like `Something.module.css` makes them importable as css classes in components.

**Comment by rohit-chaware** [comment]
Hello @hadesrofl You can use TailwindCSS which is utility first CSS framework which is comes in built with Next.js. You can use TailwindCSS to build your projects faster.

**Comment by hadesrofl** [comment]
Thanks! I'll look into it :)
